name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1) تحميل المشروع
    - name: Checkout code
      uses: actions/checkout@v4

    # 2) تثبيت Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3) تثبيت PyInstaller (ده المهم جدًا)
    - name: Install PyInstaller
      run: pip install pyinstaller

    # 4) بناء البرنامج
    - name: Build EXE
      run: python -m PyInstaller --onefile main.py

    # 5) رفع الناتج
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: dist/
